### ISSUE TITLE
NativeScript 5 support

### ISSUE THREAD

**Issue by romandrahan** [NathanaelA/nativescript-signalr#1]
@NathanaelA, does this plugin support the NativeScript 5?

**Comment by NathanaelA** [comment]
Yes, however the current version of the plugin is for the older SignalR version; not the current .Net Core version.

**Comment by romandrahan** [comment]
@NathanaelA,

Thanks for your reply. Do you know, is there any other NativeScript SignalR plugin exists for the latest .Net Core version?

Is that true, that the latest SignalR version does allow using bare WebSockets to connect to the SignalR server.
